### ISSUE TITLE
Terminology: pods, components

### ISSUE THREAD

**Issue by a-ast** [continuouspipe/documentation#47]
The `pods` concept is not very clear for beginners if they are not familiar with kubernetes https://kubernetes.io/docs/user-guide/pods/. At least a link to this page would not hurt. 
Moreover, continuouspipe UI calls it a `component`, e.g. `Logs of component elasticsearch`. So it is not clear whether it is a component or a pod.

**Comment by pswaine** [comment]
Thanks for the feedback @a-ast. You're right - the distinction isn't clear. We'll add some extra information into the docs on this, and evaluate if the UI can be improved to make it clearer.

**Comment by a-ast** [comment]
There is one more term for that
```
-s, --service string                 The service to use (e.g.: web, mysql)
```
